 - name: Download repo
   shell: sudo yum localinstall -y https://dev.mysql.com/get/mysql57-community-release-el7-11.noarch.rpm


 - name: Install MySQL
   shell: sudo yum install -y mysql-community-server

 - name: Start MySQL
   service: name=mysqld state=started enabled=true

 - name: Install Keepalived
   yum: name=keepalived state=installed

 - name: Remove ori keepalived conf file
   shell: mv /etc/keepalived/keepalived.conf /etc/keepalived/keepalived.conf.back
   ignore_errors: yes

 - name: Copy file
   copy: src=roles/templates/keepalived.conf dest=/etc/keepalived/keepalived.conf

 - name: Start Keepalived
   service: name=keepalived state=started enabled=true












